dependencies:
  - name: portfolio
    version: 1.0.0
    repository: file:///charts/portfolio
  - name: stock-quote
    version: 1.0.0
    repository: file:///charts/stock-quote
  - name: trader
    version: 1.0.0
    repository: file:///charts/trader
