#################################################################################################
#                                          SECRETS                                              #
#                                                                                               #
# These secrets will hold the configuration for the IBM StockTrader Application components.     #
# These values will be passed to their individual Helm charts which will, in turn, make them    #
# available at runtime to the application components.                                           #
#################################################################################################

secret:

  ####### Middleware #######

  db:
    # Uses the default values specified in the db2_values.yaml file in the installation/middleware folder
    create: true
    secret_name: stocktrader-db2
    # db: STOCKTRD
    db: U1RPQ0tUUkQ=
    # host: st-db2-ibm-db2oltp-dev-db2
    host: c3QtZGIyLWlibS1kYjJvbHRwLWRldi1kYjI=
    # id: db2inst1
    id: ZGIyaW5zdDE=
    # port: 50000
    port: NTAwMDA=
    # pwd: stocktraderdb
    pwd: c3RvY2t0cmFkZXJkYg==

  redis:
    # Uses the default values specified in the default_redis_values.yaml file in the installation/middleware folder
    create: true
    secret_name: stocktrader-redis
    # redis://x:redispasswd@st-redis-master:6379
    url: cmVkaXM6Ly94OnJlZGlzcGFzc3dkQHN0LXJlZGlzLW1hc3Rlcjo2Mzc5

#  mq:
#    # Uses the default values specified in the mq_values.yaml file in the installation/middleware folder
#    create: true
#    secret_name: stocktrader-mq
#    # id: app
#    id: YXBw
#    pwd: YWJjZA==
#    # host: st-mq-ibm-mq
#    host: c3QtbXEtaWJtLW1x
#    # port: 1414
#    port: MTQxNA==
#    # channel: DEV.APP.SVRCONN
#    channel: REVWLkFQUC5TVlJDT05O
#    # queue-manager: trader
#    queue_manager: dHJhZGVy
#    # queue: NotificationQ
#    queue: Tm90aWZpY2F0aW9uUQ==

  watson:
    create: true
    secret_name: stocktrader-watson
    # url: https://gateway.watsonplatform.net/tone-analyzer/api/v3/tone?version=2017-09-21&sentences=false
    url: aHR0cHM6Ly9nYXRld2F5LndhdHNvbnBsYXRmb3JtLm5ldC90b25lLWFuYWx5emVyL2FwaS92My90b25lP3ZlcnNpb249MjAxNy0wOS0yMSZzZW50ZW5jZXM9ZmFsc2U=
    # Get your credentials at https://console.bluemix.net/catalog/services/tone-analyzer
    id:
    pwd:

  odm:
    # Uses the default values specified in the default_odm_values.yaml file in the installation/middleware folder
    create: true
    secret_name: stocktrader-odm
    # url: http://st-odm-ibm-odm-dev:9060/DecisionService/rest/ICP_Trader_Dev_1/determineLoyalty
    url: aHR0cDovL3N0LW9kbS1pYm0tb2RtLWRldjo5MDYwL0RlY2lzaW9uU2VydmljZS9yZXN0L0lDUF9UcmFkZXJfRGV2XzEvZGV0ZXJtaW5lTG95YWx0eQ==

  ####### JWT #######

  jwt:
    # Uses default values for the IBM StockTrader application
    create: true
    secret_name: stocktrader-jwt
    # audience: stock-trader
    audience: c3RvY2stdHJhZGVy
    # issuer: http://stock-trader.ibm.com
    issuer: aHR0cDovL3N0b2NrLXRyYWRlci5pYm0uY29t


#################################################################################################
#                                        DEPLOYMENTS                                            #
#                                                                                               #
# The below values hold the way the IBM StockTrader Application components deployment need to   #
# be carried out and configured. There is no need to change/modify any of the below.            #
#################################################################################################

portfolio:
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    repository: ibmstocktrader
    name: portfolio
    tag: latest
    pullPolicy: Always
    containerPort:
      http: 9080
      https: 9443
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  service:
    type: ClusterIP
    servicePort:
      http: 9080
      https: 9443

###########################################

stock-quote:
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    repository: ibmstocktrader
    name: stock-quote
    tag: latest
    pullPolicy: Always
    containerPort:
      http: 9080
      https: 9443
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  service:
    type: ClusterIP
    servicePort:
      http: 9080
      https: 9443

###########################################

trader:
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    repository: ibmstocktrader
    name: trader
    tag: latest
    pullPolicy: Always
    containerPort:
      http: 9080
      https: 9443
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
  service:
    type: ClusterIP
    servicePort:
      http: 9080
      https: 9443

###########################################
