{{- if .Values.secret.mq.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.mq.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  id: {{ .Values.secret.mq.id }}
  pwd: {{ .Values.secret.mq.pwd }}
  host: {{ .Values.secret.mq.host }}
  port: {{ .Values.secret.mq.port }}
  channel: {{ .Values.secret.mq.channel }}
  queue-manager: {{ .Values.secret.mq.queue_manager }}
  queue: {{ .Values.secret.mq.queue }}
{{- end }}
