{{- if .Values.secret.db.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.db.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  db: {{ .Values.secret.db.db }}
  host: {{ .Values.secret.db.host }}
  id: {{ .Values.secret.db.id }}
  port: {{ .Values.secret.db.port }}
  pwd: {{ .Values.secret.db.pwd }}
{{- end }}
