{{- if .Values.secret.odm.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.odm.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  url: {{ .Values.secret.odm.url }}
{{- end }}
