{{- if .Values.secret.watson.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.watson.secret_name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
type: Opaque
data:
  url: {{ .Values.secret.watson.url }}
  id: {{ .Values.secret.watson.id }}
  pwd: {{ .Values.secret.watson.pwd }}
{{- end }}
